name: build
on:
  - push
jobs:
  build_project:
    runs-on: ubuntu-22.04
    steps:
      - name: "Install Go"
        uses: actions/setup-go@v5
        id: setup_go
        with:
          go-version: '1.22'

      - name: "Echo installed version"
        run: |
          echo "${{steps.setup_go.outputs.go-version}}"